// This is a simplified dataset of Duel Masters cards from sets DM-01 to DM-04
// In a real application, you would have a complete database with all card information

export const cardsData = [
  // DM-01 Base Set
  {
    id: "dm01-1",
    name: "Hanusa, Radiance Elemental",
    imageUrl: `/images/cards/sets/dm-01/dm01-1.jpg`,
    civilization: "Light",
    type: "Creature",
    race: "Angel Command",
    cost: 6,
    power: 9500,
    text: "Double breaker (This creature breaks 2 shields.)",
    set: "dm-01",
    rarity: "Very Rare",
  },
  {
    id: "dm01-2",
    name: "Urth, Purifying Elemental",
    imageUrl: `/images/cards/sets/dm-01/dm01-2.jpg`,
    civilization: "Light",
    type: "Creature",
    race: "Angel Command",
    cost: 7,
    power: 6000,
    text: "When you put this creature into the battle zone, you may return a creature from your graveyard to your hand.",
    set: "dm-01",
    rarity: "Rare",
  },
  {
    id: "dm01-3",
    name: "Szubs Kin, Twilight Guardian",
    imageUrl: `/images/cards/sets/dm-01/dm01-3.jpg`,
    civilization: "Light",
    type: "Creature",
    race: "Guardian",
    cost: 5,
    power: 5000,
    text: "Blocker (When an opponent's creature attacks, you may tap this creature to stop the attack. Then the 2 creatures battle.)",
    set: "dm-01",
    rarity: "Uncommon",
  },
  {
    id: "dm01-4",
    name: "Dia Nork, Moonlight Guardian",
    imageUrl: `/images/cards/sets/dm-01/dm01-4.jpg`,
    civilization: "Light",
    type: "Creature",
    race: "Guardian",
    cost: 4,
    power: 5000,
    text: "Blocker (When an opponent's creature attacks, you may tap this creature to stop the attack. Then the 2 creatures battle.)",
    set: "dm-01",
    rarity: "Common",
  },
  {
    id: "dm01-5",
    name: "Holy Awe",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/9/9d/Holy_Awe.jpg/revision/latest?cb=20241102093321",
    civilization: "Light",
    type: "Spell",
    cost: 6,
    text: "Tap all your opponent's creatures.",
    set: "dm-01",
    rarity: "Rare",
  },
  {
    id: "dm01-6",
    name: "Bolshack Dragon",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Bolshack_Dragon.jpg/revision/latest?cb=20241102093321",
    civilization: "Fire",
    type: "Creature",
    race: "Armored Dragon",
    cost: 6,
    power: 6000,
    text: "Double breaker (This creature breaks 2 shields.)",
    set: "dm-01",
    rarity: "Very Rare",
  },
  {
    id: "dm01-7",
    name: "Gatling Skyterror",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Gatling_Skyterror.jpg/revision/latest?cb=20241102093321",
    civilization: "Fire",
    type: "Creature",
    race: "Armored Wyvern",
    cost: 7,
    power: 7000,
    text: "Double breaker (This creature breaks 2 shields.)",
    set: "dm-01",
    rarity: "Rare",
  },
  {
    id: "dm01-8",
    name: "Brawler Zyler",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Brawler_Zyler.jpg/revision/latest?cb=20241102093321",
    civilization: "Fire",
    type: "Creature",
    race: "Human",
    cost: 2,
    power: 1000,
    text: "Power attacker +2000 (While attacking, this creature gets +2000 power.)",
    set: "dm-01",
    rarity: "Common",
  },
  {
    id: "dm01-9",
    name: "Tornado Flame",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Tornado_Flame.jpg/revision/latest?cb=20241102093321",
    civilization: "Fire",
    type: "Spell",
    cost: 5,
    text: "Destroy one of your opponent's creatures that has power 4000 or less.",
    set: "dm-01",
    rarity: "Uncommon",
  },
  {
    id: "dm01-10",
    name: "Aqua Sniper",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Aqua_Sniper.jpg/revision/latest?cb=20241102093321",
    civilization: "Water",
    type: "Creature",
    race: "Liquid People",
    cost: 6,
    power: 3000,
    text: "When you put this creature into the battle zone, your opponent chooses one of his creatures and puts it on the bottom of his deck.",
    set: "dm-01",
    rarity: "Rare",
  },
  {
    id: "dm01-11",
    name: "Crystal Paladin",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Crystal_Paladin.jpg/revision/latest?cb=20241102093321",
    civilization: "Water",
    type: "Creature",
    race: "Liquid People",
    cost: 5,
    power: 4000,
    text: "Blocker (When an opponent's creature attacks, you may tap this creature to stop the attack. Then the 2 creatures battle.)",
    set: "dm-01",
    rarity: "Uncommon",
  },
  {
    id: "dm01-12",
    name: "Brain Serum",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Brain_Serum.jpg/revision/latest?cb=20241102093321",
    civilization: "Water",
    type: "Spell",
    cost: 3,
    text: "Draw 2 cards.",
    set: "dm-01",
    rarity: "Common",
  },
  {
    id: "dm01-13",
    name: "Deathliger, Lion of Chaos",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Deathliger%2C_Lion_of_Chaos.jpg/revision/latest?cb=20241102093321",
    civilization: "Darkness",
    type: "Creature",
    race: "Demon Command",
    cost: 6,
    power: 9000,
    text: "Double breaker (This creature breaks 2 shields.)",
    set: "dm-01",
    rarity: "Very Rare",
  },
  {
    id: "dm01-14",
    name: "Dark Reversal",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Dark_Reversal.jpg/revision/latest?cb=20241102093321",
    civilization: "Darkness",
    type: "Spell",
    cost: 2,
    text: "Return a creature from your graveyard to your hand.",
    set: "dm-01",
    rarity: "Common",
  },
  {
    id: "dm01-15",
    name: "Terror Pit",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Terror_Pit.jpg/revision/latest?cb=20241102093321",
    civilization: "Darkness",
    type: "Spell",
    cost: 6,
    text: "Destroy one of your opponent's creatures.",
    set: "dm-01",
    rarity: "Rare",
  },
  {
    id: "dm01-16",
    name: "Bronze-Arm Tribe",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Bronze-Arm_Tribe.jpg/revision/latest?cb=20241102093321",
    civilization: "Nature",
    type: "Creature",
    race: "Beast Folk",
    cost: 3,
    power: 1000,
    text: "When you put this creature into the battle zone, put the top card of your deck into your mana zone.",
    set: "dm-01",
    rarity: "Common",
  },
  {
    id: "dm01-17",
    name: "Mighty Shouter",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Mighty_Shouter.jpg/revision/latest?cb=20241102093321",
    civilization: "Nature",
    type: "Creature",
    race: "Beast Folk",
    cost: 4,
    power: 2000,
    text: "When this creature would be put into your graveyard from the battle zone, put it into your mana zone instead.",
    set: "dm-01",
    rarity: "Uncommon",
  },
  {
    id: "dm01-18",
    name: "Roaring Great-Horn",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Roaring_Great-Horn.jpg/revision/latest?cb=20241102093321",
    civilization: "Nature",
    type: "Creature",
    race: "Horned Beast",
    cost: 5,
    power: 5000,
    text: "Power attacker +2000 (While attacking, this creature gets +2000 power.)",
    set: "dm-01",
    rarity: "Rare",
  },
  {
    id: "dm01-19",
    name: "Natural Snare",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Natural_Snare.jpg/revision/latest?cb=20241102093321",
    civilization: "Nature",
    type: "Spell",
    cost: 6,
    text: "Choose one of your opponent's creatures and put it on the bottom of his deck.",
    set: "dm-01",
    rarity: "Uncommon",
  },
  {
    id: "dm01-20",
    name: "Stampeding Longhorn",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Stampeding_Longhorn.jpg/revision/latest?cb=20241102093321",
    civilization: "Nature",
    type: "Creature",
    race: "Horned Beast",
    cost: 7,
    power: 8000,
    text: "Double breaker (This creature breaks 2 shields.)",
    set: "dm-01",
    rarity: "Very Rare",
  },

  // DM-02 Evo-Crushinators of Doom
  {
    id: "dm02-1",
    name: "Alcadeias, Lord of Spirits",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Alcadeias%2C_Lord_of_Spirits.jpg/revision/latest?cb=20241102093321",
    civilization: "Light",
    type: "Creature",
    race: "Angel Command",
    cost: 6,
    power: 12500,
    text: "Double breaker (This creature breaks 2 shields.)\nYour opponent can't cast spells except light spells.",
    set: "dm-02",
    rarity: "Very Rare",
  },
  {
    id: "dm02-2",
    name: "Aeris, Flight Elemental",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Aeris%2C_Flight_Elemental.jpg/revision/latest?cb=20241102093321",
    civilization: "Light",
    type: "Creature",
    race: "Angel Command",
    cost: 5,
    power: 3000,
    text: "Whenever this creature attacks, you may tap one of your opponent's creatures.",
    set: "dm-02",
    rarity: "Rare",
  },
  {
    id: "dm02-3",
    name: "Mist Rias, Sonic Guardian",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Mist_Rias%2C_Sonic_Guardian.jpg/revision/latest?cb=20241102093321",
    civilization: "Light",
    type: "Creature",
    race: "Guardian",
    cost: 4,
    power: 3000,
    text: "Blocker (When an opponent's creature attacks, you may tap this creature to stop the attack. Then the 2 creatures battle.)",
    set: "dm-02",
    rarity: "Uncommon",
  },
  {
    id: "dm02-4",
    name: "Scarlet Skyterror",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Scarlet_Skyterror.jpg/revision/latest?cb=20241102093321",
    civilization: "Fire",
    type: "Creature",
    race: "Armored Wyvern",
    cost: 8,
    power: 3000,
    text: "Triple breaker (This creature breaks 3 shields.)\nWhen you put this creature into the battle zone, destroy all other creatures.",
    set: "dm-02",
    rarity: "Very Rare",
  },
  {
    id: "dm02-5",
    name: "Explosive Fighter Ucarn",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Explosive_Fighter_Ucarn.jpg/revision/latest?cb=20241102093321",
    civilization: "Fire",
    type: "Creature",
    race: "Dragonoid",
    cost: 5,
    power: 5000,
    text: "Power attacker +4000 (While attacking, this creature gets +4000 power.)",
    set: "dm-02",
    rarity: "Rare",
  },
  {
    id: "dm02-6",
    name: "Magris, Vizier of Magnetism",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Magris%2C_Vizier_of_Magnetism.jpg/revision/latest?cb=20241102093321",
    civilization: "Water",
    type: "Creature",
    race: "Initiate",
    cost: 6,
    power: 4000,
    text: "Whenever your opponent puts a creature into the battle zone, you may draw a card.",
    set: "dm-02",
    rarity: "Rare",
  },
  {
    id: "dm02-7",
    name: "King Neptas",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/King_Neptas.jpg/revision/latest?cb=20241102093321",
    civilization: "Water",
    type: "Creature",
    race: "Leviathan",
    cost: 7,
    power: 7000,
    text: "Double breaker (This creature breaks 2 shields.)\nWhen you put this creature into the battle zone, return a creature from your graveyard to your hand.",
    set: "dm-02",
    rarity: "Very Rare",
  },
  {
    id: "dm02-8",
    name: "Ballom, Master of Death",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Ballom%2C_Master_of_Death.jpg/revision/latest?cb=20241102093321",
    civilization: "Darkness",
    type: "Creature",
    race: "Demon Command",
    cost: 8,
    power: 12000,
    text: "Double breaker (This creature breaks 2 shields.)\nWhen you put this creature into the battle zone, destroy all creatures except darkness creatures.",
    set: "dm-02",
    rarity: "Very Rare",
  },
  {
    id: "dm02-9",
    name: "Death Smoke",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Death_Smoke.jpg/revision/latest?cb=20241102093321",
    civilization: "Darkness",
    type: "Spell",
    cost: 4,
    text: "Destroy one of your opponent's untapped creatures.",
    set: "dm-02",
    rarity: "Uncommon",
  },
  {
    id: "dm02-10",
    name: "Gigargon",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Gigargon.jpg/revision/latest?cb=20241102093321",
    civilization: "Nature",
    type: "Creature",
    race: "Giant Insect",
    cost: 7,
    power: 8000,
    text: "Double breaker (This creature breaks 2 shields.)\nThis creature can't be blocked by creatures that have power 4000 or less.",
    set: "dm-02",
    rarity: "Rare",
  },

  // DM-03 Rampage of the Super Warriors
  {
    id: "dm03-1",
    name: "Astral Warper",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Astral_Warper.jpg/revision/latest?cb=20241102093321",
    civilization: "Light",
    type: "Creature",
    race: "Berserker",
    cost: 6,
    power: 2000,
    text: "When you put this creature into the battle zone, you may return a creature from your graveyard to your hand.",
    set: "dm-03",
    rarity: "Rare",
  },
  {
    id: "dm03-2",
    name: "Armored Blaster Valdios",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Armored_Blaster_Valdios.jpg/revision/latest?cb=20241102093321",
    civilization: "Fire",
    type: "Creature",
    race: "Armorloid",
    cost: 6,
    power: 6000,
    text: 'Double breaker (This creature breaks 2 shields.)\nEach of your other fire creatures in the battle zone gets +1000 power and has "power attacker +1000."',
    set: "dm-03",
    rarity: "Very Rare",
  },
  {
    id: "dm03-3",
    name: "Crystal Lancer",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Crystal_Lancer.jpg/revision/latest?cb=20241102093321",
    civilization: "Water",
    type: "Creature",
    race: "Liquid People",
    cost: 7,
    power: 5500,
    text: "Double breaker (This creature breaks 2 shields.)",
    set: "dm-03",
    rarity: "Rare",
  },
  {
    id: "dm03-4",
    name: "Zagaan, Knight of Darkness",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Zagaan%2C_Knight_of_Darkness.jpg/revision/latest?cb=20241102093321",
    civilization: "Darkness",
    type: "Creature",
    race: "Dark Lord",
    cost: 6,
    power: 11000,
    text: "Double breaker (This creature breaks 2 shields.)\nThis creature can't attack players.",
    set: "dm-03",
    rarity: "Very Rare",
  },
  {
    id: "dm03-5",
    name: "Fighter Dual Fang",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Fighter_Dual_Fang.jpg/revision/latest?cb=20241102093321",
    civilization: "Nature",
    type: "Creature",
    race: "Beast Folk",
    cost: 5,
    power: 8000,
    text: "Double breaker (This creature breaks 2 shields.)\nThis creature can't attack if you have more than 1 creature in the battle zone.",
    set: "dm-03",
    rarity: "Very Rare",
  },

  // DM-04 Shadowclash of Blinding Night
  {
    id: "dm04-1",
    name: "Ladia Bale, the Inspirational",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Ladia_Bale%2C_the_Inspirational.jpg/revision/latest?cb=20241102093321",
    civilization: "Light",
    type: "Creature",
    race: "Berserker",
    cost: 8,
    power: 15000,
    text: "Triple breaker (This creature breaks 3 shields.)\nWhen you put this creature into the battle zone, you may destroy one of your opponent's creatures that has power 2000 or less.",
    set: "dm-04",
    rarity: "Very Rare",
  },
  {
    id: "dm04-2",
    name: "Rothus, the Traveler",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Rothus%2C_the_Traveler.jpg/revision/latest?cb=20241102093321",
    civilization: "Fire",
    type: "Creature",
    race: "Armorloid",
    cost: 4,
    power: 4000,
    text: "When you put this creature into the battle zone, destroy one of your creatures and one of your opponent's creatures.",
    set: "dm-04",
    rarity: "Rare",
  },
  {
    id: "dm04-3",
    name: "Aqua Hulcus",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Aqua_Hulcus.jpg/revision/latest?cb=20241102093321",
    civilization: "Water",
    type: "Creature",
    race: "Liquid People",
    cost: 3,
    power: 1000,
    text: "When you put this creature into the battle zone, draw a card.",
    set: "dm-04",
    rarity: "Common",
  },
  {
    id: "dm04-4",
    name: "Darkbane Reaper",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Darkbane_Reaper.jpg/revision/latest?cb=20241102093321",
    civilization: "Darkness",
    type: "Creature",
    race: "Ghost",
    cost: 3,
    power: 3000,
    text: "Blocker (When an opponent's creature attacks, you may tap this creature to stop the attack. Then the 2 creatures battle.)",
    set: "dm-04",
    rarity: "Uncommon",
  },
  {
    id: "dm04-5",
    name: "Barkwhip, the Smasher",
    imageUrl: "https://static.wikia.nocookie.net/duelmasters/images/1/1d/Barkwhip%2C_the_Smasher.jpg/revision/latest?cb=20241102093321",
    civilization: "Nature",
    type: "Creature",
    race: "Beast Folk",
    cost: 4,
    power: 5000,
    text: "When you put this creature into the battle zone, one of your creatures gets +4000 power until the end of the turn.",
    set: "dm-04",
    rarity: "Rare",
  },
]

